BlogProject.Admin/Controllers/Components/PagerViewComponent.cs
using BlogProject.ViewModel.Common;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Admin.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

BlogProject.Admin/Controllers/PostController.cs
using BlogProject.Apilntegration.Category;
using BlogProject.Apilntegration.Comment;
using BlogProject.Apilntegration.Posts;
using BlogProject.Data.EF;
using BlogProject.ViewModel.Catalog.Posts;
using BlogProject.ViewModel.System.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Printing;

namespace BlogProject.Admin.Controllers
{
	[Authorize(Roles ="admin,author")]
	public class PostController : Controller
	{
		private readonly IPostApiClient _postApiClient;
		private readonly IConfiguration _configuration;
		private readonly ICategoryApiClient _categoryApiClient;
		private readonly ICommentApiClient _commentApiClient;
		private readonly BlogDbContext _context;
		public PostController(IPostApiClient postApiClient, IConfiguration configuration, ICategoryApiClient categoryApiClient, BlogDbContext context, ICommentApiClient commentApiClient)
		{
			_postApiClient = postApiClient;
			_configuration = configuration;
			_categoryApiClient = categoryApiClient;
			_context = context;
			_commentApiClient = commentApiClient;
		}

		public async Task<IActionResult> Index(int postId,string keyword, int pageIndex = 1, int pageSize = 5)
		{
			var sessions = HttpContext.Session.GetString("Token");
			var request = new GetUserPagingRequest()
			{

				Keyword = keyword,
				PageIndex = pageIndex,
				PageSize = pageSize
			};
			var checkEnable = await _postApiClient.CheckEnable(postId);
            if (checkEnable.IsSuccessed == true)
            {
                ViewBag.checkEnable = true;
            }
            else { ViewBag.checkEnable = false; }
            if (TempData["result"] != null)
			{
				ViewBag.SuccessMsg = TempData["result"];
			}
			var data = await _postApiClient.GetPagings(request);
			return View(data);
		}
		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			var result = await _postApiClient.GetById(id);



			if (result.IsSuccessed)
			{
				var post = result.ResultObj;
				var categories = await _categoryApiClient.GetAll();
				ViewBag.CategoryList = categories.Select(x => new SelectListItem()
				{
					Text = x.name,
					Value = x.id.ToString()
				});

				var updateRequest = new PostUpdateRequest()
				{
					Title = post.Title,
					Desprition = post.Desprition,
					Content = post.Content,
					ImageFileName = post.Image,
					CategoryId = post.CategoryId,

				};
				return View(updateRequest);
			}
			return RedirectToAction("Error", "Home");
		}
		[HttpPost]
		public async Task<IActionResult> Edit(PostUpdateRequest request)
		{
			if (!ModelState.IsValid)
				return View();

			var result = await _postApiClient.UpdatePost(request, request.Id);
			if (result.IsSuccessed)
			{
				TempData["result"] = "Cập nhật bài viết thành công";
				return RedirectToAction("Index");
			}

			ModelState.AddModelError("", result.Message);
			return View(request);
		}

		[HttpGet]
		public async Task<IActionResult> Create()
		{
			var categories = await _categoryApiClient.GetAll();
			ViewBag.CategoryList = categories.Select(x => new SelectListItem()
			{
				Text = x.name,
				Value = x.id.ToString()
			});
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(PostRequest request)
		{
			if (!ModelState.IsValid)
				return View(request);

			var post = await _postApiClient.CreatePost(request);
			if (post.IsSuccessed)
			{
				TempData["result"] = "Tạo bào viết thành công";
				return RedirectToAction("Index");
			}

			ModelState.AddModelError("", post.Message);
			return View(request);
		}
		[HttpGet]
		public async Task<IActionResult> Delete(int id)
		{
			return View(new PostDeleteRequest()
			{
				Id = id
			});
		}
		[HttpPost]
		public async Task<IActionResult> Delete(PostDeleteRequest request)
		{
			if (!ModelState.IsValid)
			{
				return View(request);
			}
			var post = await _postApiClient.DeletePost(request.Id);
			if (post.IsSuccessed)
			{
				TempData["result"] = "Tạo bào viết thành công";
				return RedirectToAction("Index");
			}
			ModelState.AddModelError("", post.Message);
			return View(request);
		}
		[HttpGet]
		public async Task<IActionResult> Details(int id)
		{
			var post = await _postApiClient.GetById(id);
			return View(post.ResultObj);
		}
		[HttpGet]
		public async Task<IActionResult> GetComment(int Id, string keyword, int pageIndex = 1, int pageSize = 5)
		{
			var request = new GetUserPagingRequest()
			{

				Keyword = keyword,
				PageIndex = pageIndex,
				PageSize = pageSize
			};

			if (TempData["result"] != null)
			{
				ViewBag.SuccessMsg = TempData["result"];
			}

			var data = await _commentApiClient.GetByPostId(Id, request);
			return View(data);
		}
        [HttpPost]
        public async Task<IActionResult> StatusChange( int postId , string number)
        {

            if (postId == 0)
            {
                return BadRequest();
            }
			var enable = new PostEnable()
			{
				IdPost = postId,
				Number = number
			};
            var data = await _postApiClient.StatusChange(enable);
            if (data.IsSuccessed)
            {

                return Ok(data.ResultObj);
            }
            return BadRequest();
        }
    }
}

BlogProject.Admin/Controllers/UserController.cs
using BlogProject.ViewModel.System.Users;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System.Configuration;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Security.Authentication;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;
using System.Drawing.Printing;
using Microsoft.AspNetCore.Identity;
using BlogProject.Data.Entities;
using BlogProject.ViewModel.Common;
using BlogProject.Apilntegration.Users;
using BlogProject.Apilntegration.Roles;
using Microsoft.AspNetCore.Authorization;

namespace BlogProject.Admin.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        private readonly IRoleApiClient _roleApiClient;
        public UserController(IUserApiClient userApiClient, IConfiguration configuration, IRoleApiClient roleApiClient)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
            _roleApiClient = roleApiClient;
        }
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 5)
		{
			var sessions = HttpContext.Session.GetString("Token");
			var request = new GetUserPagingRequest()
			{

				Keyword = keyword,
				PageIndex = pageIndex,
				PageSize = pageSize
			};
			if (TempData["result"] != null)
			{
				ViewBag.SuccessMsg = TempData["result"];
			}
			var data = await _userApiClient.GetUserAuthor(request);
			return View(data.ResultObj);
		}
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> ListUser(string keyword, int pageIndex = 1, int pageSize = 5)
		{
			var sessions = HttpContext.Session.GetString("Token");
			var request = new GetUserPagingRequest()
			{

				Keyword = keyword,
				PageIndex = pageIndex,
				PageSize = pageSize
			};
			if (TempData["result"] != null)
			{
				ViewBag.SuccessMsg = TempData["result"];
			}
			var data = await _userApiClient.GetUserUser(request);
			return View(data.ResultObj);
		}
		[HttpGet]
		[Authorize(Roles = "admin")]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Create(RegisterRequest request)
		{
			if (!ModelState.IsValid)
				return View();

			var result = await _userApiClient.RegisterUser(request);
			if (result.IsSuccessed)
			{
				TempData["result"] = "Thêm mới người dùng thành công";
				return RedirectToAction("Index");
			}
			ModelState.AddModelError("", result.Message);

			return View(request);
		}
		[HttpGet]
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Details(Guid id)
		{
			var user = await _userApiClient.GetById(id);
			return View(user.ResultObj);
		}
		[HttpGet]
		//[Authorize(Roles = "admin,author")]
		public async Task<IActionResult> Edit(Guid id)
		{


			var result = await _userApiClient.GetById(id);
			if (result.IsSuccessed)
			{
				var user = result.ResultObj;
				var updateRequest = new UserUpdateRequest()
				{
					Id = id,
					FirstName = user.FirstName,
					LastName = user.LastName,
					ImageFileName = user.Image,
					Email = user.Email,
					Dob = user.DateOfBir,
					Gender = user.Gender,
					PhoneNumber = user.PhoneNumber,
					Address = user.Address,
				};
				return View(updateRequest);
			}
			return RedirectToAction("Error", "Home");


		}
		[HttpPost]
		//[Authorize(Roles = "admin,author")]
		public async Task<IActionResult> Edit(UserUpdateRequest request)
		{
			if (!ModelState.IsValid)
				return View();

			var result = await _userApiClient.UpdateUser(request.Id, request);
			if (result.IsSuccessed)
			{
				TempData["result"] = "Cập nhật người dùng thành công";
				return RedirectToAction("Index");
			}

			ModelState.AddModelError("", result.Message);
			return View(request);
		}
		[HttpPost]

		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			HttpContext.Session.Remove("Token");
			return RedirectToAction("Index", "Login");
		}
		[HttpGet]
		[Authorize(Roles = "admin")]
		public IActionResult Delete(Guid id)
		{
			return View(new UserDeleteRequest()
			{
				Id = id
			});
		}
		[HttpPost]
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> Delete(UserDeleteRequest request)
		{
			if (!ModelState.IsValid)
				return View();

			var result = await _userApiClient.DeleteUser(request.Id);
			if (result.IsSuccessed)
			{
				TempData["result"] = "Xóa người dùng thành công";
				return RedirectToAction("Index");
			}

			ModelState.AddModelError("", result.Message);
			return View(request);
		}
		[HttpGet]
		//[Authorize(Roles = "admin")]
		public async Task<IActionResult> RoleAssign(Guid id)
		{
			var roleAssignRequest = await GetRoleAssignRequest(id);
			return View(roleAssignRequest);
		}

		[HttpPost]
		//[Authorize(Roles = "admin")]
		public async Task<IActionResult> RoleAssign(RoleAssignRequest request)
		{
			if (!ModelState.IsValid)
				return View();

			var result = await _userApiClient.RoleAssign(request.Id, request);

			if (result.IsSuccessed)
			{
				TempData["result"] = "Cập nhật quyền thành công";
				return RedirectToAction("Index");
			}

			ModelState.AddModelError("", result.Message);
			var roleAssignRequest = await GetRoleAssignRequest(request.Id);

			return View(roleAssignRequest);
		}
		[HttpGet]
		[Authorize(Roles = "admin,author")]
		public async Task<IActionResult> Profile(Guid id)
		{

			var profile = await _userApiClient.Profile(id);
			return View(profile.ResultObj);
		}
		[HttpGet]
		[Authorize(Roles = "admin")]
		public async Task<IActionResult> GetMonthlyStats()
		{
			return View();

		}

		[HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetMonthlyStats(int? month, int? year,string keyword, int pageIndex = 1, int pageSize = 5)
		{
            var request = new GetUserPagingRequest()
            {

                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            ViewBag.SelectedMonth = month;
            ViewBag.SelectedYear = year;
            ViewBag.Keyword = keyword;
         
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            var data = await _userApiClient.GetMonthlyStats(request, month, year);
            
            return PartialView("_UserListPartial", data.ResultObj); // Trả về một partial view
            

        }

        private async Task<RoleAssignRequest> GetRoleAssignRequest(Guid id)
		{
			var userObj = await _userApiClient.GetById(id);
			var roleObj = await _roleApiClient.GetAll();
			var roleAssignRequest = new RoleAssignRequest();
			foreach (var role in roleObj.ResultObj)
			{
				roleAssignRequest.Roles.Add(new SelectItem()
				{
					Id = role.Id.ToString(),
					Name = role.Name,
					Selected = userObj.ResultObj.Roles.Contains(role.Name)
				});
			}
			return roleAssignRequest;
		}


	}
}

BlogProject.Admin/Views/Post/Delete.cshtml
@model BlogProject.ViewModel.Catalog.Posts.PostDeleteRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PostDeleteRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BlogProject.Admin/Views/Post/Details.cshtml
@model BlogProject.ViewModel.Catalog.Posts.PostVm

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create(document.querySelector('#contentEditor'), {
            enterMode: 'br',  // Chuyển xuống dòng bằng thẻ <br> thay vì <p>
            shiftEnterMode: 'br',
            autoParagraph: false  // Tắt tự động thêm thẻ <p>
        })
        .then(editor => {
            window.editor = editor;
        })
        .catch(err => {
            console.error(err.stack);
        });
</script>
<h1 class="mt-4">Chi tiết</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
    <li class="breadcrumb-item active">Chi tiết</li>
</ol>
<div class="card mb-4">
    <div class="card-header">
        <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
    </div>

    <div class="card-body">
        <div class="col-md-14">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desprition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desprition)
        </dd>
      
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        
        <dd class="col-sm-10">
            @Html.Raw(Model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountLike)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountLike)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UploadDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.View)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.View)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            <td style="width: 10px; height: 10px; overflow: hidden;">
                <img src="@Model.Image" style="max-width: 100%; max-height: 100%; object-fit: contain;" alt="User Image">
            </td>
        </dd>
        </dl>
        </div>
    </div>
</div>

@section Scripts{


    <script>
        function toggleContent() {
            var truncatedContentElement = document.getElementById('truncatedContent');
            var remainingContentElement = document.getElementById('remainingContent');
            var readMoreLink = document.querySelector('a');

            if (truncatedContentElement.style.display === 'inline') {
                truncatedContentElement.style.display = 'none';
                remainingContentElement.style.display = 'inline';
                readMoreLink.innerHTML = 'Thu gọn';
            } else {
                truncatedContentElement.style.display = 'inline';
                remainingContentElement.style.display = 'none';
                readMoreLink.innerHTML = 'Xem thêm';
            }
        }
    </script>
    
}

BlogProject.Admin/Views/Post/Index.cshtml
@using BlogProject.ViewModel.Common;
@model PagedResult<BlogProject.ViewModel.Catalog.Posts.PostVm>
@using BlogProject.ViewModel.Catalog.Posts;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .container-fluid {
        padding: 15px;
    }

    .table {
        width: 100%;
        margin-bottom: 1rem;
        color: #212529;
    }

        .table th,
        .table td {
            padding: 0.75rem;
            vertical-align: top;
            border-top: 1px solid #dee2e6;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #dee2e6;
        }

    .table-responsive {
        display: block;
        width: 100%;
        overflow-x: auto;
    }

    .btn {
        display: inline-block;
        font-weight: 400;
        color: #212529;
        text-align: center;
        vertical-align: middle;
        user-select: none;
        background-color: transparent;
        border: 1px solid transparent;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        border-radius: 0.25rem;
        transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .btn-primary {
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-success {
        color: #fff;
        background-color: #28a745;
        border-color: #28a745;
    }

    .image-preview {
        width: 100%;
        height: auto;
        overflow: hidden;
        position: relative;
    }

        .image-preview img {
            max-width: 100%;
            max-height: 100%;
        }

    /* Base style for toggle-status button */
    .toggle-status {
        padding: 8px 12px; /* Padding around the text */
        border-radius: 5px; /* Rounded corners */
        border: none; /* Remove default border */
        color: white; /* Text color */
        font-size: 14px; /* Font size */
        cursor: pointer; /* Change cursor to pointer */
        transition: background-color 0.3s; /* Smooth transition for background color */
    }

        /* Style for enabled state (data-number="1") */
        .toggle-status[data-number="1"] {
            background-color: #28a745; /* Red background for enabled */
        }

        /* Style for disabled state (data-number="0") */
        .toggle-status[data-number="0"] {
            background-color: #dc3545; /* Green background for disabled */
        }
    /* General style for action button links */
    .action-button {
        display: inline-block; /* Display as block-level inline element */
        padding: 8px; /* Padding around the text */
        width: 80px; /* Fixed width for all buttons */
        text-align: center; /* Center the text inside the button */
        margin: 0 5px; /* Margin between buttons */
        background-color: #007bff; /* Background color */
        color: white; /* Text color */
        border-radius: 5px; /* Rounded corners */
        text-decoration: none; /* Remove underline */
        font-size: 14px; /* Font size */
        transition: background-color 0.3s; /* Smooth background color transition on hover */
        overflow: hidden; /* Hide overflow */
        white-space: nowrap; /* Prevent wrapping of text */
    }

        .action-button:hover, .action-button:focus {
            background-color: #0056b3; /* Darker shade on hover */
            color: white; /* Maintain text color on hover */
            text-decoration: none; /* Remove underline on hover */
        }

    /* Specific styles for different types of actions */
    .edit-button {
        background-color: ##007bff; /* Green background for edit */
    }

    .details-button {
        background-color: ##007bff; /* Blue background for details */
    }

    .delete-button {
        background-color: #dc3545; /* Red background for delete */
    }

    .comment-count-container {
        display: flex; /* Use flexbox for layout */
        align-items: center; /* Align items vertically in the center */
        gap: 10px; /* Space between count and button */
    }

    /* Styling for the comment count display */
    .comment-count {
        font-weight: bold; /* Make the count bold for emphasis */
        color: #555; /* Color for the comment count */
    }

    /* General style for comment action button */
    .comment-action-button {
        padding: 8px 5px; /* Padding around the text */
        background-color: #17a2b8; /* Background color */
        color: white; /* Text color */
        border-radius: 5px; /* Rounded corners */
        text-decoration: none; /* Remove underline */
        font-size: 14px; /* Font size */
        transition: background-color 0.3s; /* Smooth background color transition on hover */
    }

        .comment-action-button:hover, .comment-action-button:focus {
            background-color: #135970; /* Darker shade on hover */
            color: white; /* Maintain text color on hover */
            text-decoration: none; /* Remove underline on hover */
        }
</style>
@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        $(document).ready(function () {
            $(document).on('click', '.toggle-status', function (event) {
                var button = $(this); // Reference to the clicked button
                var postId = button.attr('data-postId'); // Lấy postId từ thuộc tính data của nút
                var currentStatus = button.attr('data-number'); // Lấy trạng thái hiện tại từ thuộc tính data
                var check = currentStatus === "1" ? 0 : 1;  // Đảo trạng thái

                $.ajax({
                    type: 'POST',
                    url: '/Post/StatusChange',
                    data: { postId: postId, number: check }, // Sửa đổi dòng này

                    success: function (response) {
                        console.log(currentStatus);
                        button.text(check === 0 ? "Enable" : "Disable");
                        // Update the data attribute for the next click
                        button.attr('data-number', check.toString());

                        // Update the button text based on the new status
                        button.text(check === 0 ? "Enable" : "Disable");
                    }

                });
            });
        });
    </script>
}
<style>
    .image-preview {
        width: 200px; /* Set your desired width */
        height: 200px; /* Set your desired height */
        overflow: hidden;
        position: relative;
    }

        .image-preview img {
            width: 100%;
            height: auto;
            display: block;
            max-width: 100%;
            max-height: 100%;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
</style>
<div class="container-fluid">
    <h1 class="mt-4">Danh sách </h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách bài viết</li>
    </ol>
    <div class="card mb-16">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Post">Tạo mới</a>
                </div>
                <div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-8">
                                <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                            </div>
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-primary">Tìm</button>
                                <button type="button" onclick="window.location.href='/User/Index'" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Tiêu đề
                            </th>

                            @*  <th>
                            Mô tả
                            </th> *@
                            <th>
                                Tên tác giả
                            </th>


                            <th>
                                Lượt thích
                            </th>
                            <th>
                                Lượt bình luận
                            </th>
                            <th>
                                Ngày tạo
                            </th>
                            <th>
                                Lượt xem
                            </th>
                            <th>
                                Thể loại
                            </th>
                            <th>
                                Hình ảnh đại diện
                            </th>
                            <th>
                                Trạng thái
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                @*  <td>
                            @Html.DisplayFor(modelItem => item.Desprition)
                            </td> *@
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>


                                <td>
                                    @Html.DisplayFor(modelItem => item.CountLike)
                                </td>
                                <td>
                                    <div class="comment-count-container">
                                        <span class="comment-count">@Html.DisplayFor(modelItem => item.CountComment)</span>
                                        @Html.ActionLink("Chi Tiết", "GetComment", new { id = item.PostID }, new { @class = "comment-action-button" })
                                    </div>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UploadDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.View)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CategoryName)
                                </td>
                                <td style="width: 150px; height: 150px; overflow: hidden;">
                                    <img src="@item.Image" style="max-width: 100%; max-height: 100%; object-fit: contain;" alt="User Image">
                                </td>
                                <td>
                                    <!-- Display enable/disable toggle button -->
                                    <button class="toggle-status" data-postId="@item.PostID" data-number="@((int)item.Active)">
                                        @(item.Active == BlogProject.Data.Enum.Active.yes ? "Disable" : "Enable")
                                    </button>
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.PostID }, new { @class = "action-button edit-button" })
                                    @Html.ActionLink("Details", "Details", new { id = item.PostID }, new { @class = "action-button details-button" })
                                    @Html.ActionLink("Delete", "Delete", new { id = item.PostID }, new { @class = "action-button delete-button" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>