BlogProject.Admin/Controllers/CategoriesController.cs
using BlogProject.Apilntegration.Category;
using BlogProject.ViewModel.Catalog.Categories;
using BlogProject.ViewModel.System.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Admin.Controllers
{
    [Authorize(Roles ="admin")]
    public class CategoriesController : Controller
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoriesController(
            ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 5)
        {

            var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _categoryApiClient.GetUsersPagings(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data.ResultObj);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var result = await _categoryApiClient.RegisterCategory(request);
            if (result.IsSuccessed != null)
            {
                TempData["result"] = "Thêm mới danh mục thành công";
                return RedirectToAction("Index");

            }

            ModelState.AddModelError("", "Thêm danh mục thất bại");
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _categoryApiClient.GetById(id);
            if (result.IsSuccessed)
            {
                var user = result.ResultObj;
                var updateRequest = new CategoryRequest()
                {
                    CategoriesID = id,
                    Name = user.Name
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CategoryRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _categoryApiClient.UpdateCategory(id, request);
            if (result.IsSuccessed != null)
            {
                TempData["result"] = "Cập nhập danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhập danh mục thất bại");
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int idCategory)
        {
            return View(new CategoryDeleteRequest()
            {
                Id = idCategory
            });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CategoryDeleteRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _categoryApiClient.DeleteCategory(request.Id);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

    }
}

BlogProject.Admin/Controllers/Components/PagerViewComponent.cs
using BlogProject.ViewModel.Common;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Admin.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

BlogProject.Admin/Views/Categories/Create.cshtml
@model BlogProject.ViewModel.Catalog.Categories.CategoryRequest
@{
    ViewData["Title"] = "Thêm danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Thêm danh mục</h1>

<hr />
<div class="col-md-12" style="padding: 1.5rem">
    <form asp-action="Create">  
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group" style="text-align: end">
            <input type="submit" value="THÊM" class="btn btn-primary" />
            <a class="btn btn-success" asp-action="Index" asp-controller="Categories">Về danh sách</a>
        </div>
    </form>
</div>
</div>

BlogProject.Admin/Views/Categories/Delete.cshtml
@model BlogProject.ViewModel.Catalog.Categories.CategoryDeleteRequest
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container-fluid">
    <h1 class="mt-4">Xóa danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Xóa danh mục</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Categories">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <span>Hãy chắc chắn rằng bạn muốn xóa danh mục này</span>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                    <div class="col-sm-4 d-xxl-inline-flex">
                        <form asp-action="Delete" style="text-align: end">
                            <input asp-for="Id" type="hidden" />
                            <input type="submit" value="Xóa" class="btn btn-danger" />
                            <a class="btn btn-success" asp-action="Index" asp-controller="Categories">Về danh sách</a>
                        </form>
                    </div>

                </dl>


            </div>
        </div>
    </div>
</div>

BlogProject.Admin/Views/Categories/Edit.cshtml
@model BlogProject.ViewModel.Catalog.Categories.CategoryRequest
@{
    ViewData["Title"] = "Chỉnh sửa danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chỉnh sửa danh mục</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
    <li class="breadcrumb-item active">Cập nhật danh mục</li>
</ol>
<hr />
<div class="col-md-12" style="padding: 1.5rem">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group" style="text-align: end">
            <input type="submit" value="Lưu" class="btn btn-primary" />
            <a class="btn btn-success" asp-action="Index" asp-controller="Categories">Về danh sách</a>
        </div>
    </form>
</div>

BlogProject.Admin/Views/Categories/Index.cshtml
@using BlogProject.ViewModel.Common;
@model PagedResult<BlogProject.ViewModel.Catalog.Categories.CategoryRequest>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Danh sách danh mục</h1>

@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
}
<div class="row">
    @if (ViewBag.SuccessMsg != null)
    {
        <div id="msgAlert" class="alert alert-success" role="alert">
            @ViewBag.SuccessMsg
        </div>
    }
</div>
<div class="card mb-12">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <a asp-action="Create" class="btn btn-success">Thêm danh mục</a>
            </div>
            <div class="col-md-6 col-xs-12">
                <form asp-action="Index" method="get">
                    <div class="row">
                        <div class="cold-md-3 user-search-btn" style="width: unset;">
                            <button type="submit" class="btn btn-primary">
                                Tìm
                            </button>
                            <button style="padding: 10px 24px; font-size: 15px;" type="button" onclick="window.location.href='/Categories/Index'" class="btn btn-dark"><i class="fa-solid fa-arrow-rotate-right"></i></button>
                        </div>
                        <div class="col-md-9" style="flex: 1;">
                            <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr class="row no-margin">
                    <th class="col-10">
                        Tên danh mục
                    </th>
                    <th class="col-2"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr class="row no-margin">
                        <td class="col-10">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="col-2">
                            <a title="Sửa" href="@Url.Action("Edit", new { id=item.CategoriesID })"><i class="fa fa-edit"></i></a>
                            <a title="Xóa" href="@Url.Action("Delete", new { idCategory=item.CategoriesID })"><i class="fa-solid fa-trash-can"></i></a>
                        </td>
                    </tr>
                }
            <td style="border-bottom: 2px solid #e9ecef; position: relative; top: -18px;"></td>

            </tbody>
        </table>
        @await Component.InvokeAsync("Pager", Model)
    </div>
</div>