BlogProject.WebBlog/Controllers/FollowController.cs
using BlogProject.Apilntegration.Posts;
using BlogProject.Apilntegration.Users;
using BlogProject.Apilntegration;
using BlogProject.ViewModel.System.Users;
using Microsoft.AspNetCore.Mvc;
using BlogProject.Apilntegration.Category;

namespace BlogProject.WebBlog.Controllers
{
	public class FollowController : Controller
	{
		private readonly IUserApiClient _userApiClient;
		private readonly IPostApiClient _postApiClient;
		private readonly ICategoryApiClient _categoryApiClient;

		public FollowController(IUserApiClient userApiClient, IPostApiClient postApiClient, ICategoryApiClient categoryApiClient)
		{
			_userApiClient = userApiClient;
			_postApiClient = postApiClient;
			_categoryApiClient = categoryApiClient;
		}


		[HttpGet]
		public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
		{

			var Category = await _categoryApiClient.GetAll();
			ViewData["Category"] = Category;
			var user = User.Identity.Name;
			
            var request = new GetUserPagingRequest()
			{
				Keyword = keyword,
				PageIndex = pageIndex,
				PageSize = pageSize,
				UserName = user
			};
			var data = await _userApiClient.GetFollowersPagings(request);
			ViewBag.Keyword = keyword;
			ViewBag.Name = user;
		
			if (TempData["result"] != null)
			{
				ViewBag.SuccessMsg = TempData["result"];
			}
			return View(data.ResultObj);
		}
		[HttpPost]
		public async Task<IActionResult> AddFollow(FollowViewModel following)
		{
			
			if (following == null)
			{
				return BadRequest();
			}
            
            var result = await _userApiClient.Follow(following);

			if (result.IsSuccessed)
			{
				return Ok();
			}
			return BadRequest();
		}

	}
}

BlogProject.WebBlog/Controllers/PostController.cs
using BlogProject.Apilntegration.Category;
using BlogProject.Apilntegration.Comment;
using BlogProject.Apilntegration.Posts;
using BlogProject.ViewModel.Catalog.Posts;
using BlogProject.ViewModel.System.Users;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BlogProject.ViewModel.Catalog.Like;
using BlogProject.ViewModel.Catalog.Comments;
using BlogProject.Apilntegration.Tags;
using BlogProject.Apilntegration.Users;

namespace BlogProject.WebBlog.Controllers
{
	public class PostController : Controller
	{
		private readonly IPostApiClient _postApiClient;
		private readonly ICommentApiClient _commentApiClient;
		private readonly ICategoryApiClient _categoryApiClient;
		private readonly IHttpContextAccessor _contextAccessor;
		private readonly ITagApiClient _tagApiClient;
        private readonly IUserApiClient _userApiClient;
        public PostController(IPostApiClient postApiClient, IUserApiClient userApiClient, ICommentApiClient commentApiClient, ICategoryApiClient categoryApiClient, IHttpContextAccessor contextAccessor,ITagApiClient tagApiClient)
		{
			_postApiClient = postApiClient;
			_commentApiClient = commentApiClient;
			_categoryApiClient = categoryApiClient;
			_contextAccessor = contextAccessor;
			_tagApiClient = tagApiClient;
            _userApiClient = userApiClient;
        }
		[HttpGet]
		public async Task<IActionResult> Detail(int id)
		{
			var likeVm = new LikeVm();

			likeVm.Id = id;
			likeVm.Username = User.Identity.Name;

			var Popular = await _postApiClient.TakeTopByQuantity(10);
			ViewData["PostPopular"] = Popular;
			var PostRecent = await _postApiClient.RecentPost(10);
			ViewData["PostRecent"] = PostRecent;
			var PostInDay = await _postApiClient.GetPostInDay();
			ViewData["PostInDay"] = PostInDay;
			var Category = await _categoryApiClient.GetAll();
			ViewData["Category"] = Category;
			var Tag = await _tagApiClient.GetAll();
			ViewData["Tag"] = Tag;
			var post = await _postApiClient.Detial(id);
			var comments = await _commentApiClient.GetAllByPostId(id);

			var checkLike = await _postApiClient.Check(likeVm);
			if (checkLike.IsSuccessed == true)
			{
				ViewBag.CheckLike = true;
			}
			else { ViewBag.CheckLike = false; }

			var model = new PostDetailRequest
			{
				Post = post.ResultObj,
				Comments = comments// Đảm bảo kiểu dữ liệu của Comments là List<CommentVm>
			};
			return View(model);
		}
		[HttpGet]
		public async Task<IActionResult> ListPostOfCategory(int categoryId)
		{
			var Category = await _categoryApiClient.GetAll();
			ViewData["Category"] = Category;

			var post = await _postApiClient.GetPostOfCategory(categoryId);

			return View(post);
		}
		[Authorize]
		[HttpPost]
		public async Task<IActionResult> Like(int postId)
		{

			if (User.Identity.Name == null)
			{
				return BadRequest();
			}

			var addlike = new LikeVm
			{


				Username = User.Identity.Name,
				Id = postId,

			};
			var result = await _postApiClient.Like(addlike);

			if (result.IsSuccessed)
			{
				return Ok();
			}

			return BadRequest();
		}

        [HttpGet]
        public async Task<IActionResult> Search(string keyword, int pageIndex = 1, int pageSize = 5)
        {

            var Category = await _categoryApiClient.GetAll();
            ViewData["Category"] = Category;
            var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };

            var data = await _postApiClient.GetAllPaging(request);
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> GetAllPage(string keyword, int pageIndex = 1, int pageSize = 5)
        {
			var Popular = await _postApiClient.TakeTopByQuantity(3);
			ViewData["PostPopular"] = Popular;
			var PostRecent = await _postApiClient.RecentPost(3);
			ViewData["PostRecent"] = PostRecent;
			var PostInDay = await _postApiClient.GetPostInDay();
			ViewData["PostInDay"] = PostInDay;
			var Category = await _categoryApiClient.GetAll();
            ViewData["Category"] = Category;
			var user = User.Identity.Name;
			var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
				UserName = user
            };

            var data = await _postApiClient.GetPagingUser(request);
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> UserPost(string userId)
        {
            var Category = await _categoryApiClient.GetAll();
            ViewData["Category"] = Category;
            var user = await _userApiClient.GetById(Guid.Parse(userId));
            ViewData["user"] = user.ResultObj;
			var followee = User.Identity.Name;
			var follower = await _userApiClient.GetById(Guid.Parse( userId));
            FollowViewModel follow = new FollowViewModel()
            {
                FolloweeName = followee,
                FollowerName = follower.ResultObj.UserName,

            };
			var followed = await _userApiClient.CheckFollow(follow);
			ViewBag.CheckFollow = followed.IsSuccessed;
			var post = await _postApiClient.GetByUserId(userId);
            return View(post);
        }
		[HttpGet]
		public async Task<IActionResult> HistoryLike(string userName)
		{
			var Category = await _categoryApiClient.GetAll();
			ViewData["Category"] = Category;
			var post = await _postApiClient.History(userName);
			return View(post);
		}
    }
}

BlogProject.WebBlog/Views/Shared/_Layout.cshtml
@using BlogProject.ViewModel.Catalog.Categories;
@{
	List<CategoryVm> categories = ViewData["Category"] as List<CategoryVm>;
}
﻿
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Katen - Trang Web Tin Tức</title>
	<meta name="description" content="Katen - Minimal Blog & Magazine HTML Theme">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.png">

	<!-- STYLES -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css" media="all">
	<link rel="stylesheet" href="~/css/all.min.css" type="text/css" media="all">
	<link rel="stylesheet" href="~/css/slick.css" type="text/css" media="all">
	<link rel="stylesheet" href="~/css/simple-line-icons.css" type="text/css" media="all">
	<link rel="stylesheet" href="~/css/style.css" type="text/css" media="all">

	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>

	<!-- preloader -->
	<div id="preloader">
		<div class="book">
			<div class="inner">
				<div class="left"></div>
				<div class="middle"></div>
				<div class="right"></div>
			</div>
			<ul>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
			</ul>
		</div>
	</div>

	<!-- site wrapper -->
	<div class="site-wrapper">

		<div class="main-overlay"></div>

		<!-- header -->
		<header class="header-default">
			<nav class="navbar navbar-expand-lg">
				<div class="container-xl">
					<!-- site logo -->
					<a class="navbar-brand" href="/home/index"><img src="~/images/logo.svg" alt="logo" /></a>

					<div class="collapse navbar-collapse">
						<!-- menus -->
						<ul class="navbar-nav mr-auto">
							<li class="nav-item ">
								<a class="nav-link " href="/home/index">Home</a>

							</li>
							<li class="nav-item">
								<a class="nav-link" href="/post/GetAllPage">News</a>
							</li>
							
					
							<li class="nav-item">
								<a class="nav-link" href="/home/Contact">Contact</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="/home/AboutUs">About Us</a>
							</li>
						</ul>
					</div>

					<!-- header right section -->
					<div class="header-right">
						<!-- social icons -->
						@* <ul class="social-icons list-unstyled list-inline mb-0">
							<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
						</ul> *@

						<ul class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="fas fa-user fa-fw"></i>
							</a>
							<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
								@if (User.Identity.IsAuthenticated)
								{
									<li><a class="dropdown-item" asp-action="AccountSetting" asp-controller="Account" asp-route-UserName="@User.Identity.Name">@User.Identity.Name</a></li>
									<li><a class="dropdown-item" asp-action="HistoryLike" asp-controller="Post" asp-route-UserName="@User.Identity.Name">Các bài viết đã thích</a></li>

									<li><a class="dropdown-item" asp-action="Index" asp-controller="Follow" asp-route-user="@User.Identity.Name">Đang theo dõi</a></li>
									<form method="post" asp-controller="Account" asp-action="Logout">
										<button type="submit" class="dropdown-item">Đăng xuất</button>
									</form>
								}
								else
								{
								
									<li><a class="dropdown-item" href="/account/Login">Đăng nhập</a></li>
									<li><a class="dropdown-item" href="/account/Register">Đăng ký</a></li>
								}
							</ul>
						</ul>
					
						<!-- header buttons -->
						<div class="header-buttons">
							<button class="search icon-button">
								<i class="icon-magnifier"></i>
							</button>
							<button class="burger-menu icon-button">
								<span class="burger-icon"></span>
							</button>
						</div>
					</div>
				</div>
			</nav>
		</header>

		@RenderBody()

		<!-- instagram feed -->
		<!-- footer -->
		<footer>
			<div class="container-xl">
				<div class="footer-inner">
					<div class="row d-flex align-items-center gy-2">
						<!-- copyright text -->
						<div class="col-md-4">
							<span class="copyright"></span>
						</div>

						<!-- social icons -->
						<div class="col-md-4">
							
						</div>


						<!-- go to top button -->
						<div class="col-md-4">
							<a href="#" id="return-to-top" class="float-md-end"><i class="icon-arrow-up"></i>Back to Top</a>
						</div>
					</div>
				</div>
			</div>
		</footer>

	</div><!-- end site wrapper -->
	<!-- search popup area -->
	<div class="search-popup">
		<!-- close button -->
		<button type="button" class="btn-close" aria-label="Close"></button>
		<!-- content -->
		<div class="search-content">
			<div class="text-center">
				<h3 class="mb-4 mt-0">Press ESC to close</h3>
			</div>
			<!-- form -->
			<form asp-action="Search" asp-controller="Post" method="get">
				<input class="form-control me-2" type="search" name="keyword" placeholder="Search and press enter ..." aria-label="Search">
				<button class="btn btn-default btn-lg" type="submit"><i class="icon-magnifier"></i></button>
			</form>
		</div>
	</div>

	<!-- canvas menu -->
	<div class="canvas-menu d-flex align-items-end flex-column">
		<!-- close button -->
		<button type="button" class="btn-close" aria-label="Close"></button>

		<!-- logo -->
		<div class="logo">
			<h2>Các Chủ Đề</h2>
		</div>

		<!-- menu -->
		<nav>
			<ul class="vertical-menu">			
				@foreach (var items in categories)
				{
					<li><a asp-action="ListPostOfCategory" asp-controller="Post" asp-route-categoryId="@items.id">@items.name</a></li>
				}
			</ul>
		</nav>

		<!-- social icons -->
		<ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
			<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
			<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
			<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
			<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
			<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
			<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
		</ul>
	</div>

	<!-- JAVA SCRIPTS -->

	<script src="~/js/jquery.min.js"></script>
	<script src="~/js/popper.min.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/slick.min.js"></script>
	<script src="~/js/jquery.sticky-sidebar.min.js"></script>
	<script src="~/js/custom.js"></script>

</body>
</html>